/* ============================================================
   N5 Vocabulary data — Lessons 1–15
   Source: "N5 Course Vocabulary List" (Attain Corp.)
   English meanings & kanji breakdowns curated for this app.
   No Chinese. Romaji is generated at runtime from the kana.
   Each word: { kana, kanji, en, pos }
   ============================================================ */

/* Single-kanji glosses — used to build the breakdown shown on
   the back of each card. Only true kanji are looked up; kana
   and symbols in a word are skipped automatically. */
const KANJI = {
  "私":"I / private","日":"day / sun","本":"book / origin / main","中":"middle / inside",
  "国":"country","韓":"Korea","大":"big","学":"study / learning","高":"tall / expensive",
  "校":"school","先":"ahead / previous","生":"life / birth","名":"name","前":"front / before",
  "方":"direction / person","来":"to come","行":"to go","友":"friend","達":"plural / to reach",
  "医":"medicine","者":"person","会":"meeting / to meet","社":"company / shrine","員":"member / staff",
  "語":"language / word","人":"person","熱":"heat / fever","寒":"cold","車":"vehicle / car",
  "山":"mountain","田":"rice field","佐":"to assist","藤":"wisteria","鈴":"bell","木":"tree / wood",
  "教":"to teach","室":"room","美":"beauty","味":"taste / flavor","同":"same","仕":"to serve",
  "事":"thing / matter","資":"resources / capital","料":"fee / materials","雑":"miscellaneous",
  "誌":"magazine / record","新":"new","聞":"to hear","写":"to copy","真":"truth / real",
  "傘":"umbrella","鞄":"bag","明":"bright","入":"to enter","茶":"tea","水":"water","紅":"crimson",
  "母":"mother","綺":"beautiful","麗":"lovely","弟":"younger brother","家":"house / home",
  "族":"tribe / family","何":"what","兄":"older brother","父":"father","全":"all / whole",
  "部":"part / section","妻":"wife","奥":"interior","二":"two","十":"ten","百":"hundred",
  "千":"thousand","万":"ten thousand","誰":"who","海":"sea","外":"outside","務":"duty",
  "手":"hand","帳":"notebook","刺":"to stab / card","年":"year","筆":"brush / pen","鉛":"lead (metal)",
  "机":"desk","椅":"chair","子":"child","時":"time / hour","計":"to measure","絵":"picture",
  "猫":"cat","犬":"dog","上":"up / above","下":"down / below","左":"left","右":"right",
  "隣":"next to","議":"discussion","午":"noon","後":"after / behind","食":"to eat / food",
  "堂":"hall","屋":"shop / roof","受":"to receive","付":"to attach","階":"floor / story",
  "段":"step / grade","動":"to move","販":"to sell / trade","売":"to sell","機":"machine",
  "課":"lesson / section","長":"long / chief","億":"hundred million","今":"now","去":"past / to leave",
  "月":"month / moon","週":"week","昨":"previous (day)","分":"minute / to divide","秒":"second",
  "半":"half","朝":"morning","昼":"noon / daytime","晩":"evening","夜":"night","休":"to rest",
  "毎":"every","誕":"birth","銀":"silver","郵":"mail / post","便":"convenience / mail",
  "局":"bureau / office","図":"diagram / plan","書":"to write / book","館":"building / hall",
  "映":"to project / reflect","画":"picture / stroke","病":"illness","院":"institution","八":"eight",
  "術":"technique / art","側":"side","曜":"day of the week","祝":"to celebrate","末":"end",
  "丈":"length / strength","夫":"husband / man","当":"to hit / this","火":"fire","土":"earth / soil",
  "阪":"slope (Osaka)","京":"capital","都":"capital / metropolis","東":"east","広":"wide","島":"island",
  "奈":"(phonetic)","良":"good","神":"god","戸":"door","横":"side / horizontal","浜":"beach",
  "城":"castle","道":"road / way","頓":"(phonetic)","堀":"moat / canal","遊":"to play",
  "園":"garden / park","地":"ground / land","金":"gold / money","閣":"palace / tower","寺":"temple",
  "張":"to stretch","疲":"to tire","支":"branch / to support","飲":"to drink","戻":"to return",
  "飯":"cooked rice / meal","酒":"alcohol / sake","理":"reason / logic","間":"interval / between",
  "習":"to learn","貸":"to lend","借":"to borrow","泳":"to swim","走":"to run","歩":"to walk",
  "結":"to tie / bind","婚":"marriage","散":"to scatter","買":"to buy","残":"to remain",
  "寿":"longevity","司":"to manage","公":"public","汁":"soup / broth","度":"degree / occurrence",
  "順":"order / sequence","秋":"autumn","葉":"leaf","原":"field / origin","座":"seat","宿":"lodging",
  "渋":"astringent","谷":"valley","浅":"shallow","橋":"bridge","野":"field","席":"seat",
  "空":"sky / empty","蔵":"storehouse","庫":"warehouse","洗":"to wash","濯":"to rinse","具":"tool / ingredient",
  "窓":"window","開":"to open","閉":"to close","電":"electricity","鉄":"iron","転":"to turn / roll",
  "幹":"trunk / main","線":"line","飛":"to fly","船":"ship / boat","駅":"station","近":"near",
  "乗":"to ride","降":"to get off / fall","見":"to see","換":"to exchange","店":"shop",
  "交":"to cross / exchange","番":"number / turn / guard","警":"to guard / warn","察":"to perceive / police",
  "署":"office / station","役":"role / service","所":"place","育":"to raise","使":"to use / envoy",
  "管":"pipe / to control","花":"flower","着":"to wear / arrive","止":"to stop","曲":"to bend / song",
  "元":"origin / source","気":"spirit / energy","企":"to plan","商":"commerce","株":"stock / stump",
  "式":"ceremony / style","師":"master / teacher","弁":"speech / dialect / valve","護":"to protect",
  "士":"samurai / expert","容":"appearance / to contain","官":"official","運":"to carry / fortune",
  "働":"to work","勉":"to strive","強":"strong","掃":"to sweep","除":"to remove","研":"to polish / study",
  "究":"to research","旅":"trip / travel","歌":"song / to sing","埼":"cape","玉":"jewel / ball",
  "静":"quiet / calm","岡":"hill","梨":"pear","持":"to hold","小":"small","吸":"to inhale",
  "住":"to live / reside","待":"to wait","寝":"to sleep","英":"England / excellent","菓":"sweets / cake",
  "腕":"arm / skill","話":"to talk / story","場":"place / venue","忙":"busy","楽":"fun / comfort / music",
  "面":"face / surface","難":"difficult","易":"easy","暑":"hot (weather)","安":"cheap / safe","古":"old",
  "悪":"bad / evil","白":"white","黒":"black","赤":"red","青":"blue","冷":"cold / to cool","暖":"warm",
  "遠":"far","狭":"narrow","速":"fast","遅":"slow / late","天":"heaven / sky","泊":"to stay overnight",
  "建":"to build","物":"thing / object","世":"world / generation","知":"to know","仮":"temporary / false",
  "漢":"China / Han","字":"character / letter","個":"individual / counter","有":"to exist / have",
  "賑":"lively","不":"not / un-","目":"eye","立":"to stand","派":"faction / group","暇":"free time",
  "変":"change / strange","町":"town","街":"street / town","牛":"cow","丼":"bowl (donburi)",
  "焼":"to grill / burn","肉":"meat","鶏":"chicken","豚":"pig","菜":"vegetable","蜜":"honey","柑":"citrus",
  "定":"to fix / set","注":"to pour / note","円":"yen / circle","別":"separate / different","活":"active / life",
  "帰":"to return home","起":"to wake / rise","漫":"cartoon / random","組":"group / to assemble",
  "果":"fruit / result","魚":"fish","音":"sound","男":"man / male","女":"woman","彼":"he / that",
  "僕":"I (male)","俺":"I (male, rough)","好":"to like / good","嫌":"to dislike","描":"to draw",
  "返":"to return (a thing)","背":"back / height","甘":"sweet","辛":"spicy / hot","苦":"bitter / painful",
  "塩":"salt","酸":"sour / acid","濃":"thick / dense","薄":"thin / weak","色":"color","荷":"load / luggage",
  "練":"to practice","浴":"to bathe","準":"standard / semi-","備":"to prepare","終":"to end","始":"to begin",
  "港":"harbor / port","歯":"tooth","磨":"to polish / brush","撮":"to photograph","作":"to make",
  "送":"to send","題":"topic / title","用":"use / business","皆":"everyone / all","庭":"garden",
  "桜":"cherry blossom","春":"spring","夏":"summer","冬":"winter","顔":"face","服":"clothes","汚":"dirty",
  "文":"sentence / writing","紙":"paper","歳":"years old / age","成":"to become / form","姉":"older sister",
  "妹":"younger sister","観":"to view","覧":"to look at","回":"time / to turn","次":"next / order",
  "雨":"rain","雪":"snow","晴":"clear (weather)","曇":"cloudy","風":"wind / style","吹":"to blow",
  "頃":"around (time)","辞":"word / to resign","授":"to grant / teach","業":"occupation / work",
  "富":"wealth / abundance","登":"to climb","試":"to try / test","勝":"to win","留":"to stay / detain",
  "調":"to investigate / tune","客":"guest / customer","和":"harmony / Japanese","拓":"to clear / open",
  "也":"(phonetic)","靴":"shoes","帽":"hat / cap","思":"to think","言":"to say / word","履":"to wear (footwear)",
  "被":"to cover / wear","脱":"to take off / escape","弾":"to play (instrument)","沖":"offshore","縄":"rope (Okinawa)",
  "北":"north","乳":"milk","供":"to offer / accompany","欲":"desire / want","一":"one","忘":"to forget",
  "予":"beforehand","約":"promise / approx.","質":"quality / substance","問":"question / to ask","答":"to answer",
  "置":"to place","頼":"to rely / request","呼":"to call","困":"to be troubled","危":"danger","暗":"dark",
  "勤":"to work / serve","徒":"follower / on foot","伝":"to convey","点":"point / dot","消":"to extinguish / erase",
  "単":"single / simple","覚":"to memorize / sense","携":"to carry / portable","帯":"belt / to wear","他":"other",
  "匹":"counter (animals)","杯":"counter (cups)","冊":"counter (books)","台":"counter (machines) / stand",
  "験":"test / effect","両":"both / counter","親":"parent / intimate","頑":"stubborn","趣":"taste / interest",
  "渡":"to cross / hand over","痛":"pain","可":"possible","愛":"love","邪":"evil / wrong","引":"to pull",
  "体":"body","頭":"head","足":"foot / leg","鼻":"nose","耳":"ear","口":"mouth","腹":"belly / stomach",
  "薬":"medicine","記":"to record","鳥":"bird","球":"ball / sphere","卓":"table / eminent","温":"warm",
  "泉":"spring / fountain","呂":"(phonetic)","短":"short","平":"flat / peace","川":"river","市":"city / market",
  "法":"law / method","符":"token / tally","喫":"to consume","合":"to fit / join","君":"you (suffix)","切":"to cut",
  "枚":"counter (flat objects)","自":"self","出":"to exit / go out","念":"thought / idea","草":"grass",
  "早":"early","利":"benefit / advantage","少":"few / little","然":"state / -ly"
};

const LESSONS = {
  "1": { jp:"第1課", grammar:"私は学生です", en:"I am a student", words:[
    {kana:"わたし", kanji:"私", en:"I / me", pos:"pronoun"},
    {kana:"あなた", kanji:"", en:"you", pos:"pronoun"},
    {kana:"さん", kanji:"", en:"Mr. / Ms. (honorific)", pos:"suffix"},
    {kana:"にほん", kanji:"日本", en:"Japan", pos:"noun · place"},
    {kana:"ちゅうごく", kanji:"中国", en:"China", pos:"noun · place"},
    {kana:"かんこく", kanji:"韓国", en:"Korea", pos:"noun · place"},
    {kana:"アメリカ", kanji:"", en:"America / USA", pos:"noun · place"},
    {kana:"インド", kanji:"", en:"India", pos:"noun · place"},
    {kana:"ドイツ", kanji:"", en:"Germany", pos:"noun · place"},
    {kana:"だいがく", kanji:"大学", en:"university", pos:"noun"},
    {kana:"こうこう", kanji:"高校", en:"high school", pos:"noun"},
    {kana:"がっこう", kanji:"学校", en:"school", pos:"noun"},
    {kana:"せんせい", kanji:"先生", en:"teacher", pos:"noun"},
    {kana:"がくせい", kanji:"学生", en:"student", pos:"noun"},
    {kana:"なまえ", kanji:"名前", en:"name", pos:"noun"},
    {kana:"あのかた", kanji:"あの方", en:"that person (polite)", pos:"pronoun · polite"},
    {kana:"から", kanji:"", en:"from", pos:"particle"},
    {kana:"くる", kanji:"来る", en:"to come", pos:"verb · G3"},
    {kana:"いく", kanji:"行く", en:"to go", pos:"verb · G1"},
    {kana:"どなた", kanji:"", en:"who (polite)", pos:"pronoun · polite"},
    {kana:"ともだち", kanji:"友達", en:"friend", pos:"noun"},
    {kana:"いしゃ", kanji:"医者", en:"doctor", pos:"noun · job"},
    {kana:"エンジニア", kanji:"", en:"engineer", pos:"noun · job"},
    {kana:"かいしゃいん", kanji:"会社員", en:"company employee", pos:"noun · job"},
    {kana:"サラリーマン", kanji:"", en:"office worker / salaryman", pos:"noun · job"},
    {kana:"おいしい", kanji:"美味しい", en:"delicious / tasty", pos:"い-adjective"},
    {kana:"おおきい", kanji:"大きい", en:"big / large", pos:"い-adjective"},
    {kana:"くに", kanji:"国", en:"country", pos:"noun"},
    {kana:"ご", kanji:"〜語", en:"language (of a country)", pos:"suffix"},
    {kana:"じん", kanji:"〜人", en:"person (of a country)", pos:"suffix"},
    {kana:"コーヒー", kanji:"", en:"coffee", pos:"noun"},
    {kana:"あつい", kanji:"熱い", en:"hot", pos:"い-adjective"},
    {kana:"さむい", kanji:"寒い", en:"cold", pos:"い-adjective"},
    {kana:"の", kanji:"", en:"'s / of (possessive)", pos:"particle"},
    {kana:"ほん", kanji:"本", en:"book", pos:"noun"},
    {kana:"くるま", kanji:"車", en:"car", pos:"noun"},
    {kana:"やまだ", kanji:"山田", en:"Yamada (surname)", pos:"noun · name"},
    {kana:"さとう", kanji:"佐藤", en:"Sato (surname)", pos:"noun · name"},
    {kana:"すずき", kanji:"鈴木", en:"Suzuki (surname)", pos:"noun · name"},
    {kana:"きょうしつ", kanji:"教室", en:"classroom", pos:"noun"},
  ]},

  "2": { jp:"第2課", grammar:"この人は誰ですか", en:"Who is this person?", words:[
    {kana:"いいえ", kanji:"", en:"no", pos:"interjection"},
    {kana:"おなじ", kanji:"同じ", en:"same", pos:"な-adjective"},
    {kana:"かいしゃ", kanji:"会社", en:"company", pos:"noun"},
    {kana:"しごと", kanji:"仕事", en:"work / job", pos:"noun"},
    {kana:"しりょう", kanji:"資料", en:"materials / documents", pos:"noun"},
    {kana:"ざっし", kanji:"雑誌", en:"magazine", pos:"noun"},
    {kana:"しんぶん", kanji:"新聞", en:"newspaper", pos:"noun"},
    {kana:"しゃしん", kanji:"写真", en:"photograph", pos:"noun"},
    {kana:"かさ", kanji:"傘", en:"umbrella", pos:"noun"},
    {kana:"かばん", kanji:"鞄", en:"bag", pos:"noun"},
    {kana:"あした", kanji:"明日", en:"tomorrow", pos:"noun"},
    {kana:"ああ", kanji:"", en:"ah / oh", pos:"interjection"},
    {kana:"どうぞ", kanji:"", en:"please / go ahead", pos:"adverb"},
    {kana:"はいる", kanji:"入る", en:"to enter", pos:"verb · G1"},
    {kana:"おちゃ", kanji:"お茶", en:"tea", pos:"noun"},
    {kana:"みず", kanji:"水", en:"water", pos:"noun"},
    {kana:"こうちゃ", kanji:"紅茶", en:"black tea", pos:"noun"},
    {kana:"ジュース", kanji:"", en:"juice", pos:"noun"},
    {kana:"この", kanji:"", en:"this (+ noun)", pos:"pre-noun"},
    {kana:"その", kanji:"", en:"that (+ noun)", pos:"pre-noun"},
    {kana:"あの", kanji:"", en:"that over there (+ noun)", pos:"pre-noun"},
    {kana:"どの", kanji:"", en:"which (+ noun)", pos:"pre-noun"},
    {kana:"これ", kanji:"", en:"this one", pos:"pronoun"},
    {kana:"それ", kanji:"", en:"that one", pos:"pronoun"},
    {kana:"あれ", kanji:"", en:"that one over there", pos:"pronoun"},
    {kana:"どれ", kanji:"", en:"which one", pos:"pronoun"},
    {kana:"ひと", kanji:"人", en:"person", pos:"noun"},
    {kana:"はは", kanji:"母", en:"(my) mother", pos:"noun"},
    {kana:"おかあさん", kanji:"お母さん", en:"(someone's) mother", pos:"noun"},
    {kana:"きれい", kanji:"綺麗", en:"pretty / clean", pos:"な-adjective"},
    {kana:"おとうと", kanji:"弟", en:"(my) younger brother", pos:"noun"},
    {kana:"かぞく", kanji:"家族", en:"family", pos:"noun"},
    {kana:"なんにん", kanji:"何人", en:"how many people", pos:"interrogative"},
    {kana:"あに", kanji:"兄", en:"(my) older brother", pos:"noun"},
    {kana:"おにいさん", kanji:"お兄さん", en:"(someone's) older brother", pos:"noun"},
    {kana:"ちち", kanji:"父", en:"(my) father", pos:"noun"},
    {kana:"ぜんぶ", kanji:"全部", en:"all / everything", pos:"noun"},
    {kana:"つま", kanji:"妻", en:"(my) wife", pos:"noun"},
    {kana:"おくさん", kanji:"奥さん", en:"(someone's) wife", pos:"noun"},
    {kana:"ふたり", kanji:"二人", en:"two people", pos:"noun"},
    {kana:"じゅう", kanji:"十", en:"ten", pos:"noun · number"},
    {kana:"ひゃく", kanji:"百", en:"hundred", pos:"noun · number"},
    {kana:"せん", kanji:"千", en:"thousand", pos:"noun · number"},
    {kana:"まん", kanji:"万", en:"ten thousand", pos:"noun · number"},
    {kana:"と", kanji:"", en:"and / with", pos:"particle"},
    {kana:"だれ", kanji:"誰", en:"who", pos:"interrogative"},
  ]},

  "3": { jp:"第3課", grammar:"会議室はどこにありますか", en:"Where is the meeting room?", words:[
    {kana:"かいがい", kanji:"海外", en:"overseas / abroad", pos:"noun"},
    {kana:"ぶ", kanji:"〜部", en:"department / division", pos:"suffix"},
    {kana:"じむ", kanji:"事務", en:"office / clerical work", pos:"noun"},
    {kana:"てちょう", kanji:"手帳", en:"pocket notebook / planner", pos:"noun"},
    {kana:"ノート", kanji:"", en:"notebook", pos:"noun"},
    {kana:"めいし", kanji:"名刺", en:"business card", pos:"noun"},
    {kana:"まんねんひつ", kanji:"万年筆", en:"fountain pen", pos:"noun"},
    {kana:"えんぴつ", kanji:"鉛筆", en:"pencil", pos:"noun"},
    {kana:"ボールペン", kanji:"", en:"ballpoint pen", pos:"noun"},
    {kana:"パソコン", kanji:"", en:"personal computer", pos:"noun"},
    {kana:"コンピューター", kanji:"", en:"computer", pos:"noun"},
    {kana:"つくえ", kanji:"机", en:"desk", pos:"noun"},
    {kana:"いす", kanji:"椅子", en:"chair", pos:"noun"},
    {kana:"とけい", kanji:"時計", en:"clock / watch", pos:"noun"},
    {kana:"え", kanji:"絵", en:"picture / painting", pos:"noun"},
    {kana:"ねこ", kanji:"猫", en:"cat", pos:"noun"},
    {kana:"いぬ", kanji:"犬", en:"dog", pos:"noun"},
    {kana:"うえ", kanji:"上", en:"up / above / on", pos:"noun · position"},
    {kana:"した", kanji:"下", en:"down / below / under", pos:"noun · position"},
    {kana:"ひだり", kanji:"左", en:"left", pos:"noun · position"},
    {kana:"みぎ", kanji:"右", en:"right", pos:"noun · position"},
    {kana:"となり", kanji:"隣", en:"next to / neighbor", pos:"noun · position"},
    {kana:"かいぎ", kanji:"会議", en:"meeting / conference", pos:"noun"},
    {kana:"かいぎしつ", kanji:"会議室", en:"meeting room", pos:"noun"},
    {kana:"ごぜん", kanji:"午前", en:"morning / a.m.", pos:"noun"},
    {kana:"ごご", kanji:"午後", en:"afternoon / p.m.", pos:"noun"},
    {kana:"ここ", kanji:"", en:"here", pos:"pronoun"},
    {kana:"そこ", kanji:"", en:"there", pos:"pronoun"},
    {kana:"あそこ", kanji:"", en:"over there", pos:"pronoun"},
    {kana:"どこ", kanji:"", en:"where", pos:"interrogative"},
    {kana:"こちら", kanji:"", en:"this way / here (polite)", pos:"pronoun · polite"},
    {kana:"そちら", kanji:"", en:"that way / there (polite)", pos:"pronoun · polite"},
    {kana:"あちら", kanji:"", en:"that way over there (polite)", pos:"pronoun · polite"},
    {kana:"どちら", kanji:"", en:"which way / where (polite)", pos:"interrogative"},
    {kana:"ある", kanji:"", en:"to exist / there is (inanimate)", pos:"verb · G1"},
    {kana:"しょくどう", kanji:"食堂", en:"cafeteria / dining hall", pos:"noun"},
    {kana:"へや", kanji:"部屋", en:"room", pos:"noun"},
    {kana:"そと", kanji:"外", en:"outside", pos:"noun · position"},
    {kana:"なか", kanji:"中", en:"inside", pos:"noun · position"},
    {kana:"うけつけ", kanji:"受付", en:"reception desk", pos:"noun"},
    {kana:"トイレ", kanji:"", en:"toilet / restroom", pos:"noun"},
    {kana:"おてあらい", kanji:"お手洗い", en:"restroom / lavatory", pos:"noun"},
    {kana:"かい", kanji:"〜階", en:"floor / story (counter)", pos:"suffix"},
    {kana:"かいだん", kanji:"階段", en:"stairs", pos:"noun"},
    {kana:"なんかい", kanji:"何階", en:"what floor / how many floors", pos:"interrogative"},
    {kana:"エレベーター", kanji:"", en:"elevator", pos:"noun"},
    {kana:"まい", kanji:"〜枚", en:"counter for flat objects", pos:"suffix"},
    {kana:"じどうはんばいき", kanji:"自動販売機", en:"vending machine", pos:"noun"},
    {kana:"かちょう", kanji:"課長", en:"section chief", pos:"noun · job"},
    {kana:"ぶちょう", kanji:"部長", en:"department manager", pos:"noun · job"},
    {kana:"しゃちょう", kanji:"社長", en:"company president", pos:"noun · job"},
    {kana:"おく", kanji:"億", en:"hundred million", pos:"noun · number"},
  ]},

  "4": { jp:"第4課", grammar:"デパートは何時から何時までですか", en:"What are the department store's hours?", words:[
    {kana:"ねん", kanji:"〜年", en:"year (counter)", pos:"counter"},
    {kana:"なんねん", kanji:"何年", en:"what year", pos:"interrogative"},
    {kana:"ことし", kanji:"今年", en:"this year", pos:"noun"},
    {kana:"らいねん", kanji:"来年", en:"next year", pos:"noun"},
    {kana:"きょねん", kanji:"去年", en:"last year", pos:"noun"},
    {kana:"がつ", kanji:"〜月", en:"month (of the year)", pos:"counter"},
    {kana:"なんがつ", kanji:"何月", en:"what month", pos:"interrogative"},
    {kana:"こんげつ", kanji:"今月", en:"this month", pos:"noun"},
    {kana:"らいげつ", kanji:"来月", en:"next month", pos:"noun"},
    {kana:"せんげつ", kanji:"先月", en:"last month", pos:"noun"},
    {kana:"しゅう", kanji:"週", en:"week", pos:"noun"},
    {kana:"こんしゅう", kanji:"今週", en:"this week", pos:"noun"},
    {kana:"らいしゅう", kanji:"来週", en:"next week", pos:"noun"},
    {kana:"せんしゅう", kanji:"先週", en:"last week", pos:"noun"},
    {kana:"ひ", kanji:"日", en:"day", pos:"noun"},
    {kana:"きょう", kanji:"今日", en:"today", pos:"noun"},
    {kana:"きのう", kanji:"昨日", en:"yesterday", pos:"noun"},
    {kana:"おととい", kanji:"", en:"the day before yesterday", pos:"noun"},
    {kana:"あさって", kanji:"", en:"the day after tomorrow", pos:"noun"},
    {kana:"じ", kanji:"〜時", en:"o'clock (counter)", pos:"counter"},
    {kana:"なんじ", kanji:"何時", en:"what time", pos:"interrogative"},
    {kana:"ふん", kanji:"〜分", en:"minute (counter)", pos:"counter"},
    {kana:"なんぷん", kanji:"何分", en:"how many minutes", pos:"interrogative"},
    {kana:"びょう", kanji:"〜秒", en:"second (counter)", pos:"counter"},
    {kana:"いつ", kanji:"", en:"when", pos:"interrogative"},
    {kana:"はん", kanji:"半", en:"half / half past", pos:"noun"},
    {kana:"まえ", kanji:"前", en:"before / front", pos:"noun"},
    {kana:"うしろ", kanji:"後ろ", en:"behind / back", pos:"noun"},
    {kana:"いま", kanji:"今", en:"now", pos:"noun"},
    {kana:"あさ", kanji:"朝", en:"morning", pos:"noun"},
    {kana:"ひる", kanji:"昼", en:"noon / daytime", pos:"noun"},
    {kana:"ばん", kanji:"晩", en:"evening / night", pos:"noun"},
    {kana:"よる", kanji:"夜", en:"night", pos:"noun"},
    {kana:"けさ", kanji:"今朝", en:"this morning", pos:"noun"},
    {kana:"こんばん", kanji:"今晩", en:"this evening / tonight", pos:"noun"},
    {kana:"やすみ", kanji:"休み", en:"rest / holiday / day off", pos:"noun"},
    {kana:"まいにち", kanji:"毎日", en:"every day", pos:"noun"},
    {kana:"まい", kanji:"毎〜", en:"every (prefix)", pos:"prefix"},
    {kana:"たんじょうび", kanji:"誕生日", en:"birthday", pos:"noun"},
    {kana:"パーティー", kanji:"", en:"party", pos:"noun"},
    {kana:"デパート", kanji:"", en:"department store", pos:"noun"},
    {kana:"ぎんこう", kanji:"銀行", en:"bank", pos:"noun"},
    {kana:"ゆうびんきょく", kanji:"郵便局", en:"post office", pos:"noun"},
    {kana:"としょかん", kanji:"図書館", en:"library", pos:"noun"},
    {kana:"えいがかん", kanji:"映画館", en:"movie theater", pos:"noun"},
    {kana:"スーパー", kanji:"", en:"supermarket", pos:"noun"},
    {kana:"びょういん", kanji:"病院", en:"hospital", pos:"noun"},
    {kana:"やおや", kanji:"八百屋", en:"greengrocer / vegetable shop", pos:"noun"},
    {kana:"びじゅつかん", kanji:"美術館", en:"art museum", pos:"noun"},
    {kana:"がわ", kanji:"〜側", en:"side (suffix)", pos:"suffix"},
    {kana:"げつようび", kanji:"月曜日", en:"Monday", pos:"noun"},
    {kana:"かようび", kanji:"火曜日", en:"Tuesday", pos:"noun"},
    {kana:"すいようび", kanji:"水曜日", en:"Wednesday", pos:"noun"},
    {kana:"もくようび", kanji:"木曜日", en:"Thursday", pos:"noun"},
    {kana:"きんようび", kanji:"金曜日", en:"Friday", pos:"noun"},
    {kana:"どようび", kanji:"土曜日", en:"Saturday", pos:"noun"},
    {kana:"にちようび", kanji:"日曜日", en:"Sunday", pos:"noun"},
    {kana:"なんようび", kanji:"何曜日", en:"what day of the week", pos:"interrogative"},
    {kana:"しゅくじつ", kanji:"祝日", en:"national holiday", pos:"noun"},
    {kana:"しゅうまつ", kanji:"週末", en:"weekend", pos:"noun"},
    {kana:"プレゼント", kanji:"", en:"present / gift", pos:"noun"},
    {kana:"だいじょうぶ", kanji:"大丈夫", en:"okay / all right", pos:"な-adjective"},
    {kana:"ほんとう", kanji:"本当", en:"true / really", pos:"noun · な-adjective"},
    {kana:"まで", kanji:"", en:"until / up to", pos:"particle"},
  ]},

  "5": { jp:"第5課", grammar:"火曜日に広島へ行きます", en:"I'm going to Hiroshima on Tuesday", words:[
    {kana:"おおさか", kanji:"大阪", en:"Osaka (place)", pos:"noun · place"},
    {kana:"きょうと", kanji:"京都", en:"Kyoto (place)", pos:"noun · place"},
    {kana:"とうきょう", kanji:"東京", en:"Tokyo (place)", pos:"noun · place"},
    {kana:"ひろしま", kanji:"広島", en:"Hiroshima (place)", pos:"noun · place"},
    {kana:"なら", kanji:"奈良", en:"Nara (place)", pos:"noun · place"},
    {kana:"こうべ", kanji:"神戸", en:"Kobe (place)", pos:"noun · place"},
    {kana:"よこはま", kanji:"横浜", en:"Yokohama (place)", pos:"noun · place"},
    {kana:"おおさかじょう", kanji:"大阪城", en:"Osaka Castle", pos:"noun · place"},
    {kana:"どうとんぼり", kanji:"道頓堀", en:"Dotonbori (place)", pos:"noun · place"},
    {kana:"ゆうえんち", kanji:"遊園地", en:"amusement park", pos:"noun"},
    {kana:"きんかくじ", kanji:"金閣寺", en:"Kinkaku-ji (Golden Pavilion)", pos:"noun · place"},
    {kana:"しゅっちょう", kanji:"出張", en:"business trip", pos:"noun · suru-verb"},
    {kana:"おみやげ", kanji:"", en:"souvenir", pos:"noun"},
    {kana:"ちょっと", kanji:"", en:"a little / a moment", pos:"adverb"},
    {kana:"つかれる", kanji:"疲れる", en:"to get tired", pos:"verb · G2"},
    {kana:"ししゃ", kanji:"支社", en:"branch office", pos:"noun"},
    {kana:"なに", kanji:"何", en:"what", pos:"interrogative"},
    {kana:"たべる", kanji:"食べる", en:"to eat", pos:"verb · G2"},
    {kana:"のむ", kanji:"飲む", en:"to drink", pos:"verb · G1"},
    {kana:"あそぶ", kanji:"遊ぶ", en:"to play / have fun", pos:"verb · G1"},
    {kana:"おこのみやき", kanji:"お好み焼き", en:"okonomiyaki (savory pancake)", pos:"noun"},
    {kana:"たこやき", kanji:"たこ焼き", en:"takoyaki (octopus balls)", pos:"noun"},
    {kana:"もどる", kanji:"戻る", en:"to return / go back", pos:"verb · G1"},
    {kana:"いっしょ", kanji:"", en:"together", pos:"adverb"},
    {kana:"ごはん", kanji:"ご飯", en:"rice / meal", pos:"noun"},
    {kana:"おさけ", kanji:"お酒", en:"alcohol / sake", pos:"noun"},
    {kana:"りょうり", kanji:"料理", en:"cooking / dish / cuisine", pos:"noun"},
    {kana:"じかん", kanji:"時間", en:"time", pos:"noun"},
    {kana:"おしえる", kanji:"教える", en:"to teach / tell", pos:"verb · G2"},
    {kana:"ならう", kanji:"習う", en:"to learn", pos:"verb · G1"},
    {kana:"する", kanji:"", en:"to do", pos:"verb · G3"},
    {kana:"かす", kanji:"貸す", en:"to lend", pos:"verb · G1"},
    {kana:"かりる", kanji:"借りる", en:"to borrow", pos:"verb · G2"},
    {kana:"およぐ", kanji:"泳ぐ", en:"to swim", pos:"verb · G1"},
    {kana:"はしる", kanji:"走る", en:"to run", pos:"verb · G1"},
    {kana:"あるく", kanji:"歩く", en:"to walk", pos:"verb · G1"},
    {kana:"けっこん", kanji:"結婚", en:"marriage", pos:"noun · suru-verb"},
    {kana:"さんぽ", kanji:"散歩", en:"a walk / stroll", pos:"noun · suru-verb"},
    {kana:"かう", kanji:"買う", en:"to buy", pos:"verb · G1"},
    {kana:"かく", kanji:"書く", en:"to write", pos:"verb · G1"},
    {kana:"だめ", kanji:"", en:"no good / not allowed", pos:"な-adjective"},
    {kana:"ざんねん", kanji:"残念", en:"regrettable / too bad", pos:"な-adjective"},
    {kana:"レポート", kanji:"", en:"report", pos:"noun"},
    {kana:"こんど", kanji:"今度", en:"this time / next time", pos:"noun"},
    {kana:"すし", kanji:"寿司", en:"sushi", pos:"noun"},
    {kana:"みそしる", kanji:"みそ汁", en:"miso soup", pos:"noun"},
    {kana:"ラーメン", kanji:"", en:"ramen", pos:"noun"},
    {kana:"コーラ", kanji:"", en:"cola", pos:"noun"},
    {kana:"おにぎり", kanji:"", en:"rice ball", pos:"noun"},
    {kana:"てんぷら", kanji:"", en:"tempura", pos:"noun"},
    {kana:"やすむ", kanji:"休む", en:"to rest / take a break", pos:"verb · G1"},
    {kana:"じゅんちょう", kanji:"順調", en:"smooth / favorable", pos:"な-adjective"},
    {kana:"こうえん", kanji:"公園", en:"park", pos:"noun"},
    {kana:"また", kanji:"", en:"again / also", pos:"adverb"},
  ]},

  "6": { jp:"第6課", grammar:"秋葉原まで、どうやって行きましたか", en:"How did you get to Akihabara?", words:[
    {kana:"あきはばら", kanji:"秋葉原", en:"Akihabara (place)", pos:"noun · place"},
    {kana:"ぎんざ", kanji:"銀座", en:"Ginza (place)", pos:"noun · place"},
    {kana:"しんじゅく", kanji:"新宿", en:"Shinjuku (place)", pos:"noun · place"},
    {kana:"しぶや", kanji:"渋谷", en:"Shibuya (place)", pos:"noun · place"},
    {kana:"あさくさ", kanji:"浅草", en:"Asakusa (place)", pos:"noun · place"},
    {kana:"しんばし", kanji:"新橋", en:"Shimbashi (place)", pos:"noun · place"},
    {kana:"うえの", kanji:"上野", en:"Ueno (place)", pos:"noun · place"},
    {kana:"せき", kanji:"席", en:"seat", pos:"noun"},
    {kana:"あく", kanji:"空く", en:"to become empty / vacant", pos:"verb · G1"},
    {kana:"あう", kanji:"会う", en:"to meet", pos:"verb · G1"},
    {kana:"れいぞうこ", kanji:"冷蔵庫", en:"refrigerator", pos:"noun"},
    {kana:"せんたくき", kanji:"洗濯機", en:"washing machine", pos:"noun"},
    {kana:"かぐ", kanji:"家具", en:"furniture", pos:"noun"},
    {kana:"エアコン", kanji:"", en:"air conditioner", pos:"noun"},
    {kana:"ドア", kanji:"", en:"door", pos:"noun"},
    {kana:"まど", kanji:"窓", en:"window", pos:"noun"},
    {kana:"あける", kanji:"開ける", en:"to open", pos:"verb · G2"},
    {kana:"しめる", kanji:"閉める", en:"to close / shut", pos:"verb · G2"},
    {kana:"うち", kanji:"家", en:"home / one's house", pos:"noun"},
    {kana:"いえ", kanji:"家", en:"house", pos:"noun"},
    {kana:"でんしゃ", kanji:"電車", en:"train", pos:"noun"},
    {kana:"ちかてつ", kanji:"地下鉄", en:"subway", pos:"noun"},
    {kana:"じてんしゃ", kanji:"自転車", en:"bicycle", pos:"noun"},
    {kana:"バス", kanji:"", en:"bus", pos:"noun"},
    {kana:"しんかんせん", kanji:"新幹線", en:"bullet train (Shinkansen)", pos:"noun"},
    {kana:"ひこうき", kanji:"飛行機", en:"airplane", pos:"noun"},
    {kana:"ふね", kanji:"船", en:"ship / boat", pos:"noun"},
    {kana:"あるいて", kanji:"歩いて", en:"on foot / walking", pos:"expression"},
    {kana:"えき", kanji:"駅", en:"station", pos:"noun"},
    {kana:"ちかく", kanji:"近く", en:"nearby / vicinity", pos:"noun · adverb"},
    {kana:"のる", kanji:"乗る", en:"to ride / get on", pos:"verb · G1"},
    {kana:"おりる", kanji:"降りる", en:"to get off / descend", pos:"verb · G2"},
    {kana:"みる", kanji:"見る", en:"to see / look / watch", pos:"verb · G2"},
    {kana:"のりかえる", kanji:"乗り換える", en:"to transfer / change (trains)", pos:"verb · G2"},
    {kana:"ふたえき", kanji:"二駅", en:"two stations", pos:"noun"},
    {kana:"みせ", kanji:"店", en:"shop / store", pos:"noun"},
    {kana:"こうばん", kanji:"交番", en:"police box", pos:"noun"},
    {kana:"けいさつしょ", kanji:"警察署", en:"police station", pos:"noun"},
    {kana:"しやくしょ", kanji:"市役所", en:"city hall", pos:"noun"},
    {kana:"どうぶつえん", kanji:"動物園", en:"zoo", pos:"noun"},
    {kana:"たいいくかん", kanji:"体育館", en:"gymnasium", pos:"noun"},
    {kana:"たいしかん", kanji:"大使館", en:"embassy", pos:"noun"},
    {kana:"にゅうこくかんりきょく", kanji:"入国管理局", en:"immigration bureau", pos:"noun"},
    {kana:"はなや", kanji:"花屋", en:"flower shop / florist", pos:"noun"},
    {kana:"つく", kanji:"着く", en:"to arrive", pos:"verb · G1"},
    {kana:"ばん", kanji:"〜番", en:"number (counter)", pos:"suffix"},
    {kana:"いりぐち", kanji:"入口", en:"entrance", pos:"noun"},
    {kana:"でぐち", kanji:"出口", en:"exit", pos:"noun"},
    {kana:"でる", kanji:"出る", en:"to go out / leave", pos:"verb · G2"},
    {kana:"はいる", kanji:"入る", en:"to enter", pos:"verb · G1"},
    {kana:"まっすぐ", kanji:"", en:"straight / straight ahead", pos:"adverb · な-adjective"},
    {kana:"まがる", kanji:"曲がる", en:"to turn / bend", pos:"verb · G1"},
    {kana:"とめる", kanji:"止める", en:"to stop / park", pos:"verb · G2"},
    {kana:"すぐ", kanji:"", en:"soon / immediately", pos:"adverb"},
  ]},

  "7": { jp:"第7課", grammar:"一緒にスキーに行きませんか", en:"Won't you go skiing together?", words:[
    {kana:"げんき", kanji:"元気", en:"healthy / energetic", pos:"noun · な-adjective"},
    {kana:"アイティーきぎょう", kanji:"IT企業", en:"IT company", pos:"noun"},
    {kana:"しょうしゃ", kanji:"商社", en:"trading company", pos:"noun"},
    {kana:"かぶしきがいしゃ", kanji:"株式会社", en:"joint-stock company / corporation", pos:"noun"},
    {kana:"メーカー", kanji:"", en:"manufacturer / maker", pos:"noun"},
    {kana:"デザイナー", kanji:"", en:"designer", pos:"noun"},
    {kana:"えきいん", kanji:"駅員", en:"station attendant", pos:"noun · job"},
    {kana:"ぎんこういん", kanji:"銀行員", en:"bank employee", pos:"noun · job"},
    {kana:"きょうし", kanji:"教師", en:"teacher / instructor", pos:"noun · job"},
    {kana:"べんごし", kanji:"弁護士", en:"lawyer", pos:"noun · job"},
    {kana:"びようし", kanji:"美容師", en:"hairdresser / beautician", pos:"noun · job"},
    {kana:"てんいん", kanji:"店員", en:"shop clerk", pos:"noun · job"},
    {kana:"けいさつかん", kanji:"警察官", en:"police officer", pos:"noun · job"},
    {kana:"うんてんしゅ", kanji:"運転手", en:"driver", pos:"noun · job"},
    {kana:"はたらく", kanji:"働く", en:"to work", pos:"verb · G1"},
    {kana:"べんきょう", kanji:"勉強", en:"study", pos:"noun · suru-verb"},
    {kana:"そうじ", kanji:"掃除", en:"cleaning", pos:"noun · suru-verb"},
    {kana:"けんきゅう", kanji:"研究", en:"research", pos:"noun · suru-verb"},
    {kana:"りょこう", kanji:"旅行", en:"travel / trip", pos:"noun · suru-verb"},
    {kana:"うたう", kanji:"歌う", en:"to sing", pos:"verb · G1"},
    {kana:"うた", kanji:"歌", en:"song", pos:"noun"},
    {kana:"カラオケ", kanji:"", en:"karaoke", pos:"noun"},
    {kana:"スキー", kanji:"", en:"skiing / ski", pos:"noun"},
    {kana:"スキーじょう", kanji:"スキー場", en:"ski resort / slope", pos:"noun"},
    {kana:"ながの", kanji:"長野", en:"Nagano (prefecture)", pos:"noun · place"},
    {kana:"ちば", kanji:"千葉", en:"Chiba (prefecture)", pos:"noun · place"},
    {kana:"かながわ", kanji:"神奈川", en:"Kanagawa (prefecture)", pos:"noun · place"},
    {kana:"さいたま", kanji:"埼玉", en:"Saitama (prefecture)", pos:"noun · place"},
    {kana:"しずおか", kanji:"静岡", en:"Shizuoka (prefecture)", pos:"noun · place"},
    {kana:"やまなし", kanji:"山梨", en:"Yamanashi (prefecture)", pos:"noun · place"},
    {kana:"アルバイト", kanji:"", en:"part-time job", pos:"noun"},
    {kana:"のみもの", kanji:"飲み物", en:"drink / beverage", pos:"noun"},
    {kana:"たべもの", kanji:"食べ物", en:"food", pos:"noun"},
    {kana:"もつ", kanji:"持つ", en:"to hold / have", pos:"verb · G1"},
    {kana:"しょうがっこう", kanji:"小学校", en:"elementary school", pos:"noun"},
    {kana:"ちゅうがっこう", kanji:"中学校", en:"junior high school", pos:"noun"},
    {kana:"タバコ", kanji:"", en:"cigarette / tobacco", pos:"noun"},
    {kana:"すう", kanji:"吸う", en:"to smoke / inhale", pos:"verb · G1"},
    {kana:"すむ", kanji:"住む", en:"to live / reside", pos:"verb · G1"},
    {kana:"まつ", kanji:"待つ", en:"to wait", pos:"verb · G1"},
    {kana:"ねる", kanji:"寝る", en:"to sleep", pos:"verb · G2"},
    {kana:"えいご", kanji:"英語", en:"English (language)", pos:"noun"},
    {kana:"おかし", kanji:"お菓子", en:"sweets / snacks", pos:"noun"},
    {kana:"うでどけい", kanji:"腕時計", en:"wristwatch", pos:"noun"},
  ]},

  "8": { jp:"第8課", grammar:"今週は、あまり寒くないです", en:"It's not very cold this week", words:[
    {kana:"でんわ", kanji:"電話", en:"telephone / phone call", pos:"noun · suru-verb"},
    {kana:"グローバル", kanji:"", en:"global", pos:"な-adjective"},
    {kana:"フランス", kanji:"", en:"France", pos:"noun · place"},
    {kana:"イタリア", kanji:"", en:"Italy", pos:"noun · place"},
    {kana:"とても", kanji:"", en:"very", pos:"adverb"},
    {kana:"あまり", kanji:"", en:"not very (+ negative)", pos:"adverb"},
    {kana:"いそがしい", kanji:"忙しい", en:"busy", pos:"い-adjective"},
    {kana:"たのしい", kanji:"楽しい", en:"fun / enjoyable", pos:"い-adjective"},
    {kana:"おもしろい", kanji:"面白い", en:"interesting / funny", pos:"い-adjective"},
    {kana:"むずかしい", kanji:"難しい", en:"difficult", pos:"い-adjective"},
    {kana:"やさしい", kanji:"易しい", en:"easy", pos:"い-adjective"},
    {kana:"おおきい", kanji:"大きい", en:"big", pos:"い-adjective"},
    {kana:"ちいさい", kanji:"小さい", en:"small", pos:"い-adjective"},
    {kana:"さむい", kanji:"寒い", en:"cold (weather)", pos:"い-adjective"},
    {kana:"あつい", kanji:"熱い／暑い", en:"hot", pos:"い-adjective"},
    {kana:"たかい", kanji:"高い", en:"tall / expensive / high", pos:"い-adjective"},
    {kana:"やすい", kanji:"安い", en:"cheap", pos:"い-adjective"},
    {kana:"あたらしい", kanji:"新しい", en:"new", pos:"い-adjective"},
    {kana:"ふるい", kanji:"古い", en:"old (things)", pos:"い-adjective"},
    {kana:"いい、よい", kanji:"良い", en:"good", pos:"い-adjective"},
    {kana:"わるい", kanji:"悪い", en:"bad", pos:"い-adjective"},
    {kana:"しろい", kanji:"白い", en:"white", pos:"い-adjective"},
    {kana:"しろ", kanji:"白", en:"white (color)", pos:"noun"},
    {kana:"くろい", kanji:"黒い", en:"black", pos:"い-adjective"},
    {kana:"くろ", kanji:"黒", en:"black (color)", pos:"noun"},
    {kana:"あかい", kanji:"赤い", en:"red", pos:"い-adjective"},
    {kana:"あか", kanji:"赤", en:"red (color)", pos:"noun"},
    {kana:"あおい", kanji:"青い", en:"blue", pos:"い-adjective"},
    {kana:"あお", kanji:"青", en:"blue (color)", pos:"noun"},
    {kana:"つめたい", kanji:"冷たい", en:"cold (to the touch)", pos:"い-adjective"},
    {kana:"あたたかい", kanji:"暖かい", en:"warm", pos:"い-adjective"},
    {kana:"ちかい", kanji:"近い", en:"near / close", pos:"い-adjective"},
    {kana:"とおい", kanji:"遠い", en:"far", pos:"い-adjective"},
    {kana:"ひろい", kanji:"広い", en:"wide / spacious", pos:"い-adjective"},
    {kana:"せまい", kanji:"狭い", en:"narrow / cramped", pos:"い-adjective"},
    {kana:"はやい", kanji:"早い／速い", en:"early / fast", pos:"い-adjective"},
    {kana:"おそい", kanji:"遅い", en:"slow / late", pos:"い-adjective"},
    {kana:"おいしい", kanji:"", en:"delicious", pos:"い-adjective"},
    {kana:"まずい", kanji:"", en:"bad-tasting", pos:"い-adjective"},
    {kana:"うまい", kanji:"", en:"tasty / skillful", pos:"い-adjective"},
    {kana:"てんき", kanji:"天気", en:"weather", pos:"noun"},
    {kana:"とまる", kanji:"泊まる", en:"to stay (overnight)", pos:"verb · G1"},
    {kana:"ホテル", kanji:"", en:"hotel", pos:"noun"},
    {kana:"たてもの", kanji:"建物", en:"building", pos:"noun"},
    {kana:"ジャパン", kanji:"", en:"Japan", pos:"noun"},
    {kana:"せわ", kanji:"世話", en:"care / help / assistance", pos:"noun"},
    {kana:"しる", kanji:"知る", en:"to know", pos:"verb · G1"},
    {kana:"ビル", kanji:"", en:"building (multi-story)", pos:"noun"},
    {kana:"ひらがな", kanji:"平仮名", en:"hiragana", pos:"noun"},
    {kana:"カタカナ", kanji:"", en:"katakana", pos:"noun"},
    {kana:"かんじ", kanji:"漢字", en:"kanji (Chinese characters)", pos:"noun"},
  ]},

  "9": { jp:"第9課", grammar:"この店は、おいしくて、とても有名ですよ", en:"This restaurant is delicious and very famous", words:[
    {kana:"ひとつ", kanji:"1つ", en:"one (thing)", pos:"counter"},
    {kana:"ふたつ", kanji:"2つ", en:"two (things)", pos:"counter"},
    {kana:"こ", kanji:"〜個", en:"counter for small objects", pos:"counter"},
    {kana:"めい", kanji:"〜名", en:"counter for people (polite)", pos:"counter"},
    {kana:"なんめい", kanji:"何名", en:"how many people (polite)", pos:"interrogative"},
    {kana:"ゆうめい", kanji:"有名", en:"famous", pos:"な-adjective"},
    {kana:"にぎやか", kanji:"賑やか", en:"lively / bustling", pos:"な-adjective"},
    {kana:"しずか", kanji:"静か", en:"quiet", pos:"な-adjective"},
    {kana:"べんり", kanji:"便利", en:"convenient", pos:"な-adjective"},
    {kana:"ふべん", kanji:"不便", en:"inconvenient", pos:"な-adjective"},
    {kana:"じょうぶ", kanji:"丈夫", en:"sturdy / durable", pos:"な-adjective"},
    {kana:"まじめ", kanji:"真面目", en:"serious / diligent", pos:"な-adjective"},
    {kana:"りっぱ", kanji:"立派", en:"splendid / fine", pos:"な-adjective"},
    {kana:"ざんねん", kanji:"残念", en:"regrettable / disappointing", pos:"な-adjective"},
    {kana:"ひま", kanji:"暇", en:"free (time) / not busy", pos:"な-adjective"},
    {kana:"たいへん", kanji:"大変", en:"tough / hard / very", pos:"な-adjective"},
    {kana:"たくさん", kanji:"", en:"a lot / many", pos:"noun · adverb"},
    {kana:"いつも", kanji:"", en:"always / usually", pos:"adverb"},
    {kana:"みち", kanji:"道", en:"road / street / way", pos:"noun"},
    {kana:"まち", kanji:"町／街", en:"town / city", pos:"noun"},
    {kana:"そば", kanji:"", en:"soba (buckwheat noodles)", pos:"noun"},
    {kana:"うどん", kanji:"", en:"udon (noodles)", pos:"noun"},
    {kana:"ぎゅうどん", kanji:"牛丼", en:"beef bowl", pos:"noun"},
    {kana:"やきにく", kanji:"焼肉", en:"grilled meat / yakiniku", pos:"noun"},
    {kana:"にく", kanji:"肉", en:"meat", pos:"noun"},
    {kana:"とりにく", kanji:"鶏肉", en:"chicken (meat)", pos:"noun"},
    {kana:"ぶたにく", kanji:"豚肉", en:"pork", pos:"noun"},
    {kana:"ぎゅうにく", kanji:"牛肉", en:"beef", pos:"noun"},
    {kana:"やさい", kanji:"野菜", en:"vegetable", pos:"noun"},
    {kana:"やきそば", kanji:"焼きそば", en:"yakisoba (fried noodles)", pos:"noun"},
    {kana:"カレー（ライス）", kanji:"", en:"curry (rice)", pos:"noun"},
    {kana:"ピザ", kanji:"", en:"pizza", pos:"noun"},
    {kana:"ハンバーガー", kanji:"", en:"hamburger", pos:"noun"},
    {kana:"サンドイッチ", kanji:"", en:"sandwich", pos:"noun"},
    {kana:"リンゴ", kanji:"", en:"apple", pos:"noun"},
    {kana:"みかん", kanji:"蜜柑", en:"mandarin orange", pos:"noun"},
    {kana:"なし", kanji:"梨", en:"pear", pos:"noun"},
    {kana:"ていしょく", kanji:"定食", en:"set meal", pos:"noun"},
    {kana:"ウェイトレス", kanji:"", en:"waitress", pos:"noun"},
    {kana:"ちゅうもん", kanji:"注文", en:"order (in a restaurant)", pos:"noun · suru-verb"},
    {kana:"かいけい", kanji:"会計", en:"bill / check / accounting", pos:"noun · suru-verb"},
    {kana:"えん", kanji:"円", en:"yen", pos:"noun"},
    {kana:"べつべつ", kanji:"別々", en:"separately", pos:"noun · な-adjective"},
    {kana:"レストラン", kanji:"", en:"restaurant", pos:"noun"},
    {kana:"ところ", kanji:"所", en:"place", pos:"noun"},
    {kana:"とき", kanji:"時", en:"time / when", pos:"noun"},
    {kana:"ミス", kanji:"", en:"mistake", pos:"noun"},
    {kana:"せいかつ", kanji:"生活", en:"life / living", pos:"noun · suru-verb"},
    {kana:"かえる", kanji:"帰る", en:"to return / go home", pos:"verb · G1"},
    {kana:"おきる", kanji:"起きる", en:"to get up / wake up", pos:"verb · G2"},
  ]},

  "10": { jp:"第10課", grammar:"秋葉原へ、まんがを買いに行きます", en:"I'm going to Akihabara to buy manga", words:[
    {kana:"まんが", kanji:"漫画", en:"manga / comic", pos:"noun"},
    {kana:"アニメ", kanji:"", en:"anime", pos:"noun"},
    {kana:"テレビドラマ", kanji:"", en:"TV drama", pos:"noun"},
    {kana:"ばんぐみ", kanji:"番組", en:"(TV/radio) program", pos:"noun"},
    {kana:"くだもの", kanji:"果物", en:"fruit", pos:"noun"},
    {kana:"さかな", kanji:"魚", en:"fish", pos:"noun"},
    {kana:"ダンス", kanji:"", en:"dance / dancing", pos:"noun · suru-verb"},
    {kana:"スポーツ", kanji:"", en:"sport / sports", pos:"noun"},
    {kana:"おんがく", kanji:"音楽", en:"music", pos:"noun"},
    {kana:"かね", kanji:"金", en:"money", pos:"noun"},
    {kana:"チケット", kanji:"", en:"ticket", pos:"noun"},
    {kana:"きっぷ", kanji:"切符", en:"ticket (transport)", pos:"noun"},
    {kana:"おとこ", kanji:"男", en:"man / male", pos:"noun"},
    {kana:"おんな", kanji:"女", en:"woman / female", pos:"noun"},
    {kana:"かれ", kanji:"彼", en:"he / boyfriend", pos:"noun · pronoun"},
    {kana:"かのじょ", kanji:"彼女", en:"she / girlfriend", pos:"noun · pronoun"},
    {kana:"ぼく", kanji:"僕", en:"I / me (male)", pos:"pronoun"},
    {kana:"おれ", kanji:"俺", en:"I / me (male, casual)", pos:"pronoun"},
    {kana:"すき", kanji:"好き", en:"like / fond of", pos:"な-adjective"},
    {kana:"きらい", kanji:"嫌い", en:"dislike / hate", pos:"な-adjective"},
    {kana:"じょうず", kanji:"上手", en:"skillful / good at", pos:"な-adjective"},
    {kana:"へた", kanji:"下手", en:"unskillful / bad at", pos:"な-adjective"},
    {kana:"わかる", kanji:"分かる", en:"to understand", pos:"verb · G1"},
    {kana:"ほんや", kanji:"本屋", en:"bookstore", pos:"noun"},
    {kana:"コンビニ", kanji:"", en:"convenience store", pos:"noun"},
    {kana:"きっさてん", kanji:"喫茶店", en:"café / coffee shop", pos:"noun"},
    {kana:"きって", kanji:"切手", en:"postage stamp", pos:"noun"},
    {kana:"すこし", kanji:"少し", en:"a little / a few", pos:"adverb"},
    {kana:"ぜんぜん", kanji:"全然", en:"(not) at all (+ negative)", pos:"adverb"},
    {kana:"え", kanji:"絵", en:"drawing / picture", pos:"noun"},
    {kana:"えがく", kanji:"描く", en:"to draw / paint", pos:"verb · G1"},
    {kana:"あげる", kanji:"", en:"to give", pos:"verb · G2"},
    {kana:"もらう", kanji:"", en:"to receive", pos:"verb · G1"},
    {kana:"かえす", kanji:"返す", en:"to return / give back", pos:"verb · G1"},
    {kana:"せ", kanji:"背", en:"height / back", pos:"noun"},
    {kana:"レンタルショップ", kanji:"", en:"rental shop", pos:"noun"},
    {kana:"あまい", kanji:"甘い", en:"sweet", pos:"い-adjective"},
    {kana:"からい", kanji:"辛い", en:"spicy / hot", pos:"い-adjective"},
    {kana:"にがい", kanji:"苦い", en:"bitter", pos:"い-adjective"},
    {kana:"しおからい", kanji:"塩辛い", en:"salty", pos:"い-adjective"},
    {kana:"すっぱい", kanji:"酸っぱい", en:"sour", pos:"い-adjective"},
    {kana:"こい", kanji:"濃い", en:"thick / strong (flavor)", pos:"い-adjective"},
    {kana:"うすい", kanji:"薄い", en:"thin / weak (flavor)", pos:"い-adjective"},
    {kana:"もの", kanji:"物", en:"thing / object", pos:"noun"},
    {kana:"いろ", kanji:"色", en:"color", pos:"noun"},
    {kana:"かかる", kanji:"", en:"to take (time) / cost", pos:"verb · G1"},
    {kana:"どうして", kanji:"", en:"why / how come", pos:"interrogative"},
  ]},

  "11": { jp:"第11課", grammar:"安藤さんは、電話をかけています", en:"Mr. Ando is making a phone call", words:[
    {kana:"にもつ", kanji:"荷物", en:"luggage / baggage", pos:"noun"},
    {kana:"かいもの", kanji:"買い物", en:"shopping", pos:"noun · suru-verb"},
    {kana:"せんたく", kanji:"洗濯", en:"laundry / washing", pos:"noun · suru-verb"},
    {kana:"れんしゅう", kanji:"練習", en:"practice", pos:"noun · suru-verb"},
    {kana:"あらう", kanji:"洗う", en:"to wash", pos:"verb · G1"},
    {kana:"あびる", kanji:"浴びる", en:"to take (a shower) / bathe", pos:"verb · G2"},
    {kana:"シャワー", kanji:"", en:"shower", pos:"noun"},
    {kana:"じゅんび", kanji:"準備", en:"preparation", pos:"noun · suru-verb"},
    {kana:"まだ", kanji:"", en:"still / not yet", pos:"adverb"},
    {kana:"もう", kanji:"", en:"already / now", pos:"adverb"},
    {kana:"おわる", kanji:"終わる", en:"to end / finish", pos:"verb · G1"},
    {kana:"はじまる", kanji:"始まる", en:"to begin / start", pos:"verb · G1"},
    {kana:"くうこう", kanji:"空港", en:"airport", pos:"noun"},
    {kana:"チェックイン", kanji:"", en:"check-in", pos:"noun · suru-verb"},
    {kana:"チェックアウト", kanji:"", en:"check-out", pos:"noun · suru-verb"},
    {kana:"は", kanji:"歯", en:"tooth / teeth", pos:"noun"},
    {kana:"みがく", kanji:"磨く", en:"to brush / polish", pos:"verb · G1"},
    {kana:"とる", kanji:"撮る", en:"to take (a photo)", pos:"verb · G1"},
    {kana:"つくる", kanji:"作る", en:"to make", pos:"verb · G1"},
    {kana:"すわる", kanji:"座る", en:"to sit", pos:"verb · G1"},
    {kana:"おくる", kanji:"送る", en:"to send", pos:"verb · G1"},
    {kana:"じゅう", kanji:"〜中", en:"throughout / all over", pos:"suffix"},
    {kana:"ラジオ", kanji:"", en:"radio", pos:"noun"},
    {kana:"きく", kanji:"聞く", en:"to listen / hear / ask", pos:"verb · G1"},
    {kana:"だす", kanji:"出す", en:"to take out / send out", pos:"verb · G1"},
    {kana:"しゅくだい", kanji:"宿題", en:"homework", pos:"noun"},
    {kana:"ようじ", kanji:"用事", en:"errand / things to do", pos:"noun"},
    {kana:"みなさん", kanji:"皆さん", en:"everyone (polite)", pos:"noun"},
    {kana:"にわ", kanji:"庭", en:"garden / yard", pos:"noun"},
    {kana:"さくら", kanji:"桜", en:"cherry blossom", pos:"noun"},
    {kana:"き", kanji:"木", en:"tree", pos:"noun"},
    {kana:"はる", kanji:"春", en:"spring", pos:"noun"},
    {kana:"なつ", kanji:"夏", en:"summer", pos:"noun"},
    {kana:"あき", kanji:"秋", en:"autumn / fall", pos:"noun"},
    {kana:"ふゆ", kanji:"冬", en:"winter", pos:"noun"},
    {kana:"べんとう", kanji:"弁当", en:"boxed lunch (bento)", pos:"noun"},
    {kana:"て", kanji:"手", en:"hand", pos:"noun"},
    {kana:"かお", kanji:"顔", en:"face", pos:"noun"},
    {kana:"ふく", kanji:"服", en:"clothes", pos:"noun"},
    {kana:"きたない", kanji:"汚い", en:"dirty / messy", pos:"い-adjective"},
    {kana:"かいわ", kanji:"会話", en:"conversation", pos:"noun · suru-verb"},
    {kana:"ぶんぽう", kanji:"文法", en:"grammar", pos:"noun"},
    {kana:"てがみ", kanji:"手紙", en:"letter", pos:"noun"},
    {kana:"さい", kanji:"〜歳", en:"years old (counter)", pos:"counter"},
    {kana:"いくつ", kanji:"", en:"how many / how old", pos:"interrogative"},
    {kana:"なる", kanji:"", en:"to become", pos:"verb · G1"},
  ]},

  "12": { jp:"第12課", grammar:"明日の天気を調べるね", en:"I'll check tomorrow's weather", words:[
    {kana:"あね", kanji:"姉", en:"(my) older sister", pos:"noun"},
    {kana:"おねえさん", kanji:"お姉さん", en:"(someone's) older sister", pos:"noun"},
    {kana:"いもうと", kanji:"妹", en:"(my) younger sister", pos:"noun"},
    {kana:"おとうと", kanji:"弟", en:"(my) younger brother", pos:"noun"},
    {kana:"おば", kanji:"", en:"(my) aunt", pos:"noun"},
    {kana:"おばさん", kanji:"", en:"aunt / middle-aged woman", pos:"noun"},
    {kana:"おじ", kanji:"", en:"(my) uncle", pos:"noun"},
    {kana:"おじさん", kanji:"", en:"uncle / middle-aged man", pos:"noun"},
    {kana:"ちゃん", kanji:"", en:"affectionate suffix (children/friends)", pos:"suffix"},
    {kana:"くん", kanji:"", en:"suffix for boys / juniors", pos:"suffix"},
    {kana:"ハッピーゆうえんち", kanji:"ハッピー遊園地", en:"Happy Amusement Park", pos:"noun · place"},
    {kana:"かんらんしゃ", kanji:"観覧車", en:"Ferris wheel", pos:"noun"},
    {kana:"ぜんかい", kanji:"前回", en:"last time", pos:"noun"},
    {kana:"じかい", kanji:"次回", en:"next time", pos:"noun"},
    {kana:"あめ", kanji:"雨", en:"rain", pos:"noun"},
    {kana:"ゆき", kanji:"雪", en:"snow", pos:"noun"},
    {kana:"はれ", kanji:"晴れ", en:"clear / sunny weather", pos:"noun"},
    {kana:"くもり", kanji:"曇り", en:"cloudy weather", pos:"noun"},
    {kana:"かぜ", kanji:"風", en:"wind", pos:"noun"},
    {kana:"はれる", kanji:"晴れる", en:"to clear up", pos:"verb · G2"},
    {kana:"ふる", kanji:"降る", en:"to fall (rain / snow)", pos:"verb · G1"},
    {kana:"ふく", kanji:"吹く", en:"to blow (wind)", pos:"verb · G1"},
    {kana:"ごろ", kanji:"頃", en:"around / about (time)", pos:"suffix"},
    {kana:"じしょ", kanji:"辞書", en:"dictionary", pos:"noun"},
    {kana:"でんしじしょ", kanji:"電子辞書", en:"electronic dictionary", pos:"noun"},
    {kana:"じゅぎょう", kanji:"授業", en:"class / lesson", pos:"noun"},
    {kana:"ふじさん", kanji:"富士山", en:"Mt. Fuji", pos:"noun · place"},
    {kana:"やま", kanji:"山", en:"mountain", pos:"noun"},
    {kana:"のぼる", kanji:"登る", en:"to climb", pos:"verb · G1"},
    {kana:"しあい", kanji:"試合", en:"match / game", pos:"noun"},
    {kana:"かつ", kanji:"勝つ", en:"to win", pos:"verb · G1"},
    {kana:"りゅうがく", kanji:"留学", en:"studying abroad", pos:"noun · suru-verb"},
    {kana:"なつやすみ", kanji:"夏休み", en:"summer vacation", pos:"noun"},
    {kana:"ふゆやすみ", kanji:"冬休み", en:"winter vacation", pos:"noun"},
    {kana:"はるやすみ", kanji:"春休み", en:"spring vacation", pos:"noun"},
    {kana:"しらべる", kanji:"調べる", en:"to investigate / look up", pos:"verb · G2"},
    {kana:"でかける", kanji:"出かける", en:"to go out", pos:"verb · G2"},
    {kana:"きゃく", kanji:"客", en:"guest / customer", pos:"noun"},
    {kana:"てんちょう", kanji:"店長", en:"store manager", pos:"noun · job"},
    {kana:"ケーキ", kanji:"", en:"cake", pos:"noun"},
    {kana:"みのり", kanji:"", en:"Minori (name)", pos:"noun · name"},
    {kana:"かずこ", kanji:"和子", en:"Kazuko (name)", pos:"noun · name"},
    {kana:"たくや", kanji:"拓也", en:"Takuya (name)", pos:"noun · name"},
    {kana:"アパート", kanji:"", en:"apartment", pos:"noun"},
    {kana:"マンション", kanji:"", en:"condominium / apartment", pos:"noun"},
  ]},

  "13": { jp:"第13課", grammar:"私は、新しい靴を買いたいです", en:"I want to buy new shoes", words:[
    {kana:"くつ", kanji:"靴", en:"shoes", pos:"noun"},
    {kana:"くつした", kanji:"靴下", en:"socks", pos:"noun"},
    {kana:"ハンカチ", kanji:"", en:"handkerchief", pos:"noun"},
    {kana:"ぼうし", kanji:"帽子", en:"hat / cap", pos:"noun"},
    {kana:"うわぎ", kanji:"上着", en:"jacket / coat", pos:"noun"},
    {kana:"コート", kanji:"", en:"coat", pos:"noun"},
    {kana:"ズボン", kanji:"", en:"trousers / pants", pos:"noun"},
    {kana:"くつや", kanji:"靴屋", en:"shoe store", pos:"noun"},
    {kana:"ぱんや", kanji:"パン屋", en:"bakery", pos:"noun"},
    {kana:"パン", kanji:"", en:"bread", pos:"noun"},
    {kana:"さかなや", kanji:"魚屋", en:"fish shop", pos:"noun"},
    {kana:"おもう", kanji:"思う", en:"to think / feel", pos:"verb · G1"},
    {kana:"いう", kanji:"言う", en:"to say", pos:"verb · G1"},
    {kana:"サイズ", kanji:"", en:"size", pos:"noun"},
    {kana:"メートル", kanji:"", en:"meter", pos:"noun"},
    {kana:"センチ", kanji:"", en:"centimeter", pos:"noun"},
    {kana:"はく", kanji:"履く", en:"to wear (lower body / footwear)", pos:"verb · G1"},
    {kana:"きる", kanji:"着る", en:"to wear (upper body)", pos:"verb · G2"},
    {kana:"かぶる", kanji:"被る", en:"to wear (on the head)", pos:"verb · G1"},
    {kana:"ぬぐ", kanji:"脱ぐ", en:"to take off (clothes)", pos:"verb · G1"},
    {kana:"ひく", kanji:"弾く", en:"to play (an instrument)", pos:"verb · G1"},
    {kana:"ギター", kanji:"", en:"guitar", pos:"noun"},
    {kana:"ピアノ", kanji:"", en:"piano", pos:"noun"},
    {kana:"コンサート", kanji:"", en:"concert", pos:"noun"},
    {kana:"ちょうど", kanji:"", en:"exactly / just right", pos:"adverb"},
    {kana:"もちろん", kanji:"", en:"of course", pos:"adverb"},
    {kana:"いくら", kanji:"", en:"how much", pos:"interrogative"},
    {kana:"ドル", kanji:"", en:"dollar", pos:"noun"},
    {kana:"より", kanji:"", en:"than (comparison)", pos:"particle"},
    {kana:"いちばん", kanji:"一番", en:"the most / number one", pos:"noun · adverb"},
    {kana:"ほしい", kanji:"欲しい", en:"to want / desire", pos:"い-adjective"},
    {kana:"おきなわ", kanji:"沖縄", en:"Okinawa (place)", pos:"noun · place"},
    {kana:"ほっかいどう", kanji:"北海道", en:"Hokkaido (place)", pos:"noun · place"},
    {kana:"ヨーロッパ", kanji:"", en:"Europe", pos:"noun · place"},
    {kana:"アジア", kanji:"", en:"Asia", pos:"noun · place"},
    {kana:"イタリア", kanji:"", en:"Italy", pos:"noun · place"},
    {kana:"タイ", kanji:"", en:"Thailand", pos:"noun · place"},
    {kana:"マレーシア", kanji:"", en:"Malaysia", pos:"noun · place"},
    {kana:"インドネシア", kanji:"", en:"Indonesia", pos:"noun · place"},
    {kana:"どう", kanji:"", en:"how", pos:"interrogative"},
    {kana:"ぎゅうにゅう", kanji:"牛乳", en:"milk", pos:"noun"},
    {kana:"こども", kanji:"子供", en:"child", pos:"noun"},
    {kana:"ほう", kanji:"方", en:"direction / side / way", pos:"noun"},
    {kana:"ピンク", kanji:"", en:"pink", pos:"noun"},
    {kana:"ビール", kanji:"", en:"beer", pos:"noun"},
  ]},

  "14": { jp:"第14課", grammar:"午後7時に、駅に来てください", en:"Please come to the station at 7 PM", words:[
    {kana:"ぼうねんかい", kanji:"忘年会", en:"year-end party", pos:"noun"},
    {kana:"しんねんかい", kanji:"新年会", en:"New Year's party", pos:"noun"},
    {kana:"よやく", kanji:"予約", en:"reservation / appointment", pos:"noun · suru-verb"},
    {kana:"はなす", kanji:"話す", en:"to speak / talk", pos:"verb · G1"},
    {kana:"しつもん", kanji:"質問", en:"question", pos:"noun · suru-verb"},
    {kana:"もんだい", kanji:"問題", en:"problem / question", pos:"noun"},
    {kana:"こたえる", kanji:"答える", en:"to answer", pos:"verb · G2"},
    {kana:"こたえ", kanji:"答え", en:"answer", pos:"noun"},
    {kana:"おく", kanji:"置く", en:"to put / place", pos:"verb · G1"},
    {kana:"うる", kanji:"売る", en:"to sell", pos:"verb · G1"},
    {kana:"たのむ", kanji:"頼む", en:"to ask / request", pos:"verb · G1"},
    {kana:"よぶ", kanji:"呼ぶ", en:"to call", pos:"verb · G1"},
    {kana:"こまる", kanji:"困る", en:"to be troubled / in trouble", pos:"verb · G1"},
    {kana:"あぶない", kanji:"危ない", en:"dangerous", pos:"い-adjective"},
    {kana:"あかるい", kanji:"明るい", en:"bright / cheerful", pos:"い-adjective"},
    {kana:"くらい", kanji:"暗い", en:"dark", pos:"い-adjective"},
    {kana:"でんわかいぎ", kanji:"電話会議", en:"conference call", pos:"noun"},
    {kana:"タクシー", kanji:"", en:"taxi", pos:"noun"},
    {kana:"つとめる", kanji:"勤める", en:"to work for / be employed", pos:"verb · G2"},
    {kana:"つぎ", kanji:"次", en:"next", pos:"noun"},
    {kana:"クラス", kanji:"", en:"class", pos:"noun"},
    {kana:"テスト", kanji:"", en:"test", pos:"noun"},
    {kana:"せいと", kanji:"生徒", en:"student / pupil", pos:"noun"},
    {kana:"てつだう", kanji:"手伝う", en:"to help / assist", pos:"verb · G1"},
    {kana:"たつ", kanji:"立つ", en:"to stand", pos:"verb · G1"},
    {kana:"みせる", kanji:"見せる", en:"to show", pos:"verb · G2"},
    {kana:"しょうがくせい", kanji:"小学生", en:"elementary school student", pos:"noun"},
    {kana:"ちゅうがくせい", kanji:"中学生", en:"junior high school student", pos:"noun"},
    {kana:"こうこうせい", kanji:"高校生", en:"high school student", pos:"noun"},
    {kana:"だいがくせい", kanji:"大学生", en:"university student", pos:"noun"},
    {kana:"ねんせい", kanji:"〜年生", en:"(grade)-year student", pos:"suffix"},
    {kana:"でんき", kanji:"電気", en:"electricity / light", pos:"noun"},
    {kana:"つける", kanji:"点ける", en:"to turn on (light)", pos:"verb · G2"},
    {kana:"けす", kanji:"消す", en:"to turn off / erase", pos:"verb · G1"},
    {kana:"しゅっせき", kanji:"出席", en:"attendance", pos:"noun · suru-verb"},
    {kana:"たんご", kanji:"単語", en:"word / vocabulary", pos:"noun"},
    {kana:"おぼえる", kanji:"覚える", en:"to remember / memorize", pos:"verb · G2"},
    {kana:"わすれる", kanji:"忘れる", en:"to forget", pos:"verb · G2"},
    {kana:"けいたいでんわ", kanji:"携帯電話", en:"mobile phone", pos:"noun"},
    {kana:"つかう", kanji:"使う", en:"to use", pos:"verb · G1"},
    {kana:"うまれる", kanji:"生まれる", en:"to be born", pos:"verb · G2"},
    {kana:"はじめて", kanji:"", en:"for the first time", pos:"adverb"},
    {kana:"みんな", kanji:"", en:"everyone / all", pos:"noun"},
    {kana:"ほか", kanji:"他", en:"other / another", pos:"noun"},
    {kana:"かい", kanji:"〜回", en:"counter for times / occurrences", pos:"counter"},
    {kana:"ひき", kanji:"〜匹", en:"counter for small animals", pos:"counter"},
    {kana:"はい", kanji:"〜杯", en:"counter for cupfuls / glasses", pos:"counter"},
    {kana:"ほん", kanji:"〜本", en:"counter for long objects", pos:"counter"},
    {kana:"さつ", kanji:"〜冊", en:"counter for books / volumes", pos:"counter"},
    {kana:"だい", kanji:"〜台", en:"counter for machines / vehicles", pos:"counter"},
    {kana:"テープ", kanji:"", en:"tape", pos:"noun"},
    {kana:"あげる", kanji:"上げる", en:"to raise / lift", pos:"verb · G2"},
  ]},

  "15": { jp:"第15課", grammar:"昨日、図書館に本を返すことが出来ませんでした", en:"Yesterday I couldn't return the book to the library", words:[
    {kana:"しけん", kanji:"試験", en:"exam / test", pos:"noun"},
    {kana:"りゅうがくせい", kanji:"留学生", en:"international student", pos:"noun"},
    {kana:"りょうしん", kanji:"両親", en:"parents", pos:"noun"},
    {kana:"よく", kanji:"", en:"often / well", pos:"adverb"},
    {kana:"もっと", kanji:"", en:"more", pos:"adverb"},
    {kana:"がんばる", kanji:"頑張る", en:"to do one's best / persevere", pos:"verb · G1"},
    {kana:"とぶ", kanji:"飛ぶ", en:"to fly / jump", pos:"verb · G1"},
    {kana:"しゅみ", kanji:"趣味", en:"hobby", pos:"noun"},
    {kana:"きえる", kanji:"消える", en:"to disappear / go out", pos:"verb · G2"},
    {kana:"わたす", kanji:"渡す", en:"to hand over / pass", pos:"verb · G1"},
    {kana:"わたる", kanji:"渡る", en:"to cross (over)", pos:"verb · G1"},
    {kana:"いたい", kanji:"痛い", en:"painful / sore", pos:"い-adjective"},
    {kana:"かわいい", kanji:"可愛い", en:"cute", pos:"い-adjective"},
    {kana:"かぜ", kanji:"風邪", en:"a cold (illness)", pos:"noun"},
    {kana:"ひく", kanji:"引く", en:"to pull / catch (a cold)", pos:"verb · G1"},
    {kana:"からだ", kanji:"体", en:"body", pos:"noun"},
    {kana:"あたま", kanji:"頭", en:"head", pos:"noun"},
    {kana:"あし", kanji:"足", en:"leg / foot", pos:"noun"},
    {kana:"め", kanji:"目", en:"eye", pos:"noun"},
    {kana:"はな", kanji:"鼻", en:"nose", pos:"noun"},
    {kana:"みみ", kanji:"耳", en:"ear", pos:"noun"},
    {kana:"くち", kanji:"口", en:"mouth", pos:"noun"},
    {kana:"かお", kanji:"顔", en:"face", pos:"noun"},
    {kana:"おなか", kanji:"お腹", en:"stomach / belly", pos:"noun"},
    {kana:"びょうき", kanji:"病気", en:"illness / sickness", pos:"noun"},
    {kana:"くすり", kanji:"薬", en:"medicine", pos:"noun"},
    {kana:"にっき", kanji:"日記", en:"diary", pos:"noun"},
    {kana:"どうぶつ", kanji:"動物", en:"animal", pos:"noun"},
    {kana:"とり", kanji:"鳥", en:"bird", pos:"noun"},
    {kana:"インターネット", kanji:"", en:"Internet", pos:"noun"},
    {kana:"うんてん", kanji:"運転", en:"driving", pos:"noun · suru-verb"},
    {kana:"やきゅう", kanji:"野球", en:"baseball", pos:"noun"},
    {kana:"たっきゅう", kanji:"卓球", en:"table tennis / ping-pong", pos:"noun"},
    {kana:"サッカー", kanji:"", en:"soccer", pos:"noun"},
    {kana:"バスケットボール", kanji:"", en:"basketball", pos:"noun"},
    {kana:"プール", kanji:"", en:"swimming pool", pos:"noun"},
    {kana:"うみ", kanji:"海", en:"sea / ocean", pos:"noun"},
    {kana:"そら", kanji:"空", en:"sky", pos:"noun"},
    {kana:"しかし", kanji:"", en:"however / but", pos:"conjunction"},
    {kana:"できる", kanji:"出来る", en:"to be able to / can", pos:"verb · G2"},
    {kana:"ふろ", kanji:"お風呂", en:"bath", pos:"noun"},
    {kana:"おんせん", kanji:"温泉", en:"hot spring", pos:"noun"},
    {kana:"だいどころ", kanji:"台所", en:"kitchen", pos:"noun"},
    {kana:"ながい", kanji:"長い", en:"long", pos:"い-adjective"},
    {kana:"みじかい", kanji:"短い", en:"short", pos:"い-adjective"},
    {kana:"はし", kanji:"橋", en:"bridge", pos:"noun"},
    {kana:"わね", kanji:"", en:"isn't it? (sentence-ending)", pos:"interjection"},
  ]},
};

/* Expose for Node-based testing as well as the browser. */
if (typeof module !== "undefined" && module.exports) {
  module.exports = { LESSONS, KANJI };
}
