/* ============================================================
   Grammar Review 1 — Week 1 (Days 1–4, 16–19 Jun)
   Covers: Genki L1–5 / Attain L1–8
     • L1–3 : です・か・の・これ/それ/あれ・この/その/あの・も・を・へ/に・ませんか
     • L4   : あります/います・location & position・past tense・から〜まで・time/dates
     • L5   : verb groups & forms・い-adjectives (present/past/+noun/いい)

   Question types
     • mcq   : options[] + answer (exact text of the correct option)
     • short : accept[]  (any normalised match counts correct); `answer`
               is the canonical answer shown in the review.

   Short-answer grading is lenient (see normalise() in app.js): whitespace
   is stripped, ASCII is lower-cased, and a trailing です is ignored, so the
   learner can type kana or kanji and need not add です unless it's the point.
   ============================================================ */

const REVIEW = {
  id: "review-1",
  title: "Grammar Review 1",
  subtitle:
    "Week 1 · Genki L1–5 — existence, past tense, から〜まで, verbs & い-adjectives",
  questions: [
    /* ---------- Section A · L1–L3 foundations ---------- */
    {
      type: "mcq",
      topic: "は (topic)",
      prompt: "わたし ___ ジョンです。",
      sub: "“I am John.” — choose the particle.",
      options: ["は", "を", "が", "に"],
      answer: "は",
      explain: "は marks the topic: 「わたしは…です」.",
    },
    {
      type: "mcq",
      topic: "Question か",
      prompt: "Turn 「これは ペンです」 into a question.",
      sub: "What do you add at the end?",
      options: ["か", "ね", "よ", "の"],
      answer: "か",
      explain: "Adding か makes a polite question: これは ペンですか。",
    },
    {
      type: "short",
      topic: "の (possession)",
      prompt: "“Mr. Tanaka’s teacher” = たなかさん ___ せんせい。",
      sub: "Fill in the particle (kana).",
      accept: ["の"],
      answer: "の",
      explain: "の links two nouns: A の B = “B of A”.",
    },
    {
      type: "mcq",
      topic: "これ/それ/あれ",
      prompt: "An object near the LISTENER (away from you) is…",
      sub: "Choose the right demonstrative.",
      options: ["それ", "これ", "あれ", "どれ"],
      answer: "それ",
      explain: "これ=near me, それ=near you, あれ=away from both, どれ=which.",
    },
    {
      type: "mcq",
      topic: "この/その/あの",
      prompt: "Which is correct for “this book”?",
      sub: "この vs これ.",
      options: ["この ほん", "これ ほん", "この ほんです か", "これの ほん"],
      answer: "この ほん",
      explain:
        "この/その/あの attach directly to a noun (この ほん). これ/それ/あれ stand alone.",
    },
    {
      type: "short",
      topic: "じゃありません",
      prompt: "Make 「がくせいです」 negative: “(I) am not a student.”",
      sub: "Polite negative of です.",
      accept: [
        "がくせいじゃありません",
        "がくせいではありません",
        "がくせいじゃないです",
        "学生じゃありません",
        "学生ではありません",
      ],
      answer: "がくせいじゃありません",
      explain: "Polite negative of です: じゃありません (= ではありません).",
    },
    {
      type: "mcq",
      topic: "も (also)",
      prompt: "「わたしも がくせいです」 — も means…",
      sub: "",
      options: ["also / too", "but", "only", "and"],
      answer: "also / too",
      explain: "も replaces は/が and means “also / too”.",
    },
    {
      type: "mcq",
      topic: "を (object)",
      prompt: "「パンを たべます」 — を marks the…",
      sub: "",
      options: [
        "direct object",
        "topic",
        "location of existence",
        "direction",
      ],
      answer: "direct object",
      explain: "を marks the direct object of an action verb.",
    },
    {
      type: "short",
      topic: "へ/に (direction)",
      prompt: "“I go to school.” = がっこう ___ いきます。",
      sub: "Particle for destination (give the one written へ).",
      accept: ["へ", "え"],
      answer: "へ",
      explain:
        "へ marks direction/destination of motion verbs (に also works here).",
    },
    {
      type: "mcq",
      topic: "〜ませんか",
      prompt: "「いっしょに いきませんか」 expresses…",
      sub: "",
      options: [
        "an invitation (“won’t you…?”)",
        "a command",
        "a past action",
        "a reason",
      ],
      answer: "an invitation (“won’t you…?”)",
      explain: "Vませんか is a polite invitation: “Won’t you ~ / shall we ~?”",
    },
    {
      type: "short",
      topic: "ます negative",
      prompt: "Negative polite of 「のみます」 = “(I) don’t drink.”",
      sub: "",
      accept: ["のみません", "飲みません"],
      answer: "のみません",
      explain: "Polite non-past negative: ます → ません.",
    },

    /* ---------- Section B · L4 existence & location ---------- */
    {
      type: "mcq",
      topic: "あります/います",
      prompt: "「いぬが ___」 (a dog exists).",
      sub: "Animate or inanimate?",
      options: ["います", "あります", "です", "いきます"],
      answer: "います",
      explain: "います = living things (people/animals); あります = inanimate.",
    },
    {
      type: "mcq",
      topic: "あります/います",
      prompt: "「つくえの うえに ほんが ___」 (a book is on the desk).",
      sub: "",
      options: ["あります", "います", "です", "あれます"],
      answer: "あります",
      explain: "Books are inanimate → あります.",
    },
    {
      type: "short",
      topic: "location に",
      prompt: "“There is a cat under the table.” つくえの した ___ ねこが います。",
      sub: "Fill the particle (kana).",
      accept: ["に"],
      answer: "に",
      explain: "に marks the place where something exists (place に N があります/います).",
    },
    {
      type: "mcq",
      topic: "Position words",
      prompt: "「となり」 means…",
      sub: "",
      options: ["next to", "below", "in front of", "inside"],
      answer: "next to",
      explain: "となり=next to, した=below, まえ=in front, なか=inside.",
    },
    {
      type: "short",
      topic: "Position words",
      prompt: "“behind / in back of” = ___",
      sub: "Write in kana.",
      accept: ["うしろ", "後ろ", "うしろ "],
      answer: "うしろ（後ろ）",
      explain: "うしろ = behind; opposite of まえ (front).",
    },
    {
      type: "short",
      topic: "Position words",
      prompt: "“on top of / above” = ___",
      sub: "Write in kana.",
      accept: ["うえ", "上"],
      answer: "うえ（上）",
      explain: "うえ = above/on; した = below/under.",
    },
    {
      type: "mcq",
      topic: "Position words",
      prompt: "Which pair is correctly matched?",
      sub: "",
      options: [
        "ひだり = left / みぎ = right",
        "ひだり = right / みぎ = left",
        "みぎ = above / ひだり = below",
        "みぎ = next to / ひだり = inside",
      ],
      answer: "ひだり = left / みぎ = right",
      explain: "ひだり = left, みぎ = right.",
    },

    /* ---------- Section C · L4 past tense, duration, から〜まで, time ---------- */
    {
      type: "short",
      topic: "です past",
      prompt: "Past of です: “(It) was a student.” → がくせい ___",
      sub: "Polite past of です.",
      accept: ["でした"],
      answer: "でした",
      explain: "Polite past of です is でした.",
    },
    {
      type: "short",
      topic: "です past negative",
      prompt: "“(It) was not a teacher.” → せんせい ___",
      sub: "Polite past-negative of です.",
      accept: [
        "じゃありませんでした",
        "ではありませんでした",
        "じゃなかったです",
      ],
      answer: "じゃありませんでした",
      explain: "Past negative of です: じゃ/では ありませんでした.",
    },
    {
      type: "short",
      topic: "Verb past",
      prompt: "Past polite of 「たべます」 = “(I) ate.”",
      sub: "",
      accept: ["たべました", "食べました"],
      answer: "たべました",
      explain: "Polite past affirmative: ます → ました.",
    },
    {
      type: "mcq",
      topic: "Verb past negative",
      prompt: "Past negative of 「のみます」 = “(I) did not drink.”",
      sub: "",
      options: [
        "のみませんでした",
        "のみませんだ",
        "のまませんでした",
        "のみましたない",
      ],
      answer: "のみませんでした",
      explain: "Polite past negative: ます → ませんでした.",
    },
    {
      type: "short",
      topic: "Verb past negative",
      prompt: "“(I) didn’t go.” from 「いきます」 → ___",
      sub: "",
      accept: ["いきませんでした", "行きませんでした"],
      answer: "いきませんでした",
      explain: "いきます → いきませんでした.",
    },
    {
      type: "mcq",
      topic: "から〜まで",
      prompt: "「9じから 5じまで」 means…",
      sub: "",
      options: [
        "from 9 o’clock to/until 5 o’clock",
        "about 9 to 5",
        "before 9, after 5",
        "9 or 5 o’clock",
      ],
      answer: "from 9 o’clock to/until 5 o’clock",
      explain: "から = from (start), まで = to/until (end).",
    },
    {
      type: "short",
      topic: "から〜まで",
      prompt: "“from Monday to Friday” = げつようび ___ きんようび ___",
      sub: "Fill both particles, separated by a space.",
      accept: ["からまで", "から まで", "から、まで"],
      answer: "から … まで",
      explain: "X から Y まで = “from X to Y”.",
    },
    {
      type: "mcq",
      topic: "Time reading",
      prompt: "How is 「4時」 read?",
      sub: "",
      options: ["よじ", "よんじ", "しじ", "よっじ"],
      answer: "よじ",
      explain: "4時 = よじ (irregular; not よんじ).",
    },
    {
      type: "short",
      topic: "Time reading",
      prompt: "How is 「9時」 read? (kana)",
      sub: "",
      accept: ["くじ"],
      answer: "くじ",
      explain: "9時 = くじ (irregular; not きゅうじ).",
    },
    {
      type: "short",
      topic: "Date reading",
      prompt: "How is 「4月」 (April) read? (kana)",
      sub: "",
      accept: ["しがつ"],
      answer: "しがつ",
      explain: "April = しがつ (not よんがつ / よんげつ).",
    },
    {
      type: "mcq",
      topic: "Date reading",
      prompt: "How is 「20日」 (the 20th) read?",
      sub: "",
      options: ["はつか", "にじゅうにち", "はたち", "ふつか"],
      answer: "はつか",
      explain: "20日 = はつか (irregular). はたち is 20 years old.",
    },
    {
      type: "short",
      topic: "Duration",
      prompt: "“two hours” = ___",
      sub: "Write in kana.",
      accept: ["にじかん", "2じかん", "２じかん"],
      answer: "にじかん",
      explain: "Duration uses 〜じかん: にじかん = 2 hours.",
    },

    /* ---------- Section D · L5 verbs ---------- */
    {
      type: "mcq",
      topic: "Verb groups",
      prompt: "Which group is 「たべる」?",
      sub: "",
      options: ["Group 2", "Group 1", "Group 3", "irregular only"],
      answer: "Group 2",
      explain: "たべる ends in -eru → Group 2 (ichidan).",
    },
    {
      type: "mcq",
      topic: "Verb groups",
      prompt: "Which group is 「のむ」?",
      sub: "",
      options: ["Group 1", "Group 2", "Group 3", "い-adjective"],
      answer: "Group 1",
      explain: "のむ ends in -u (not -iru/-eru) → Group 1 (godan).",
    },
    {
      type: "mcq",
      topic: "Verb groups",
      prompt: "Which group is 「する」?",
      sub: "",
      options: ["Group 3", "Group 1", "Group 2", "Group 4"],
      answer: "Group 3",
      explain: "する and くる are the two Group 3 (irregular) verbs.",
    },
    {
      type: "mcq",
      topic: "Verb groups (trap)",
      prompt: "「かえる」 (to return home) looks like Group 2 but is actually…",
      sub: "",
      options: ["Group 1", "Group 2", "Group 3", "an adjective"],
      answer: "Group 1",
      explain:
        "かえる・はいる・しる・はしる・きる end in -iru/-eru but are Group 1 exceptions.",
    },
    {
      type: "short",
      topic: "ます-form",
      prompt: "ます-form of 「かく」 (to write) = ___",
      sub: "",
      accept: ["かきます", "書きます"],
      answer: "かきます",
      explain: "Group 1: -u → -i + ます. かく → かきます.",
    },
    {
      type: "short",
      topic: "ます-form",
      prompt: "ます-form of 「たべる」 = ___",
      sub: "",
      accept: ["たべます", "食べます"],
      answer: "たべます",
      explain: "Group 2: drop る, add ます.",
    },
    {
      type: "short",
      topic: "ます-form",
      prompt: "ます-form of 「くる」 (to come) = ___",
      sub: "",
      accept: ["きます", "来ます"],
      answer: "きます",
      explain: "Group 3 irregular: くる → きます.",
    },
    {
      type: "mcq",
      topic: "Verb forms",
      prompt: "Which is NOT one of the five verb forms?",
      sub: "",
      options: ["めい形", "辞書形 (dictionary)", "ない形", "て形"],
      answer: "めい形",
      explain: "The five forms: 辞書形・ます形・ない形・た形・て形. めい形 isn’t one.",
    },
    {
      type: "short",
      topic: "Dictionary form",
      prompt: "What dictionary form would you look up for 「のみます」?",
      sub: "",
      accept: ["のむ", "飲む"],
      answer: "のむ",
      explain: "のみます → dictionary form のむ.",
    },

    /* ---------- Section E · L5 い-adjectives ---------- */
    {
      type: "short",
      topic: "い-adj negative",
      prompt: "Negative of 「おおきい」 = “not big”.",
      sub: "Plain or です form both fine.",
      accept: [
        "おおきくない",
        "おおきくないです",
        "大きくない",
        "大きくないです",
      ],
      answer: "おおきくない",
      explain: "い-adj negative: drop い → くない. おおきい → おおきくない.",
    },
    {
      type: "short",
      topic: "い-adj past",
      prompt: "Past of 「たかい」 = “was expensive / tall”.",
      sub: "",
      accept: ["たかかった", "高かった", "たかかったです", "高かったです"],
      answer: "たかかった",
      explain: "い-adj past: drop い → かった. たかい → たかかった.",
    },
    {
      type: "short",
      topic: "い-adj past negative",
      prompt: "Past negative of 「さむい」 = “was not cold”.",
      sub: "",
      accept: [
        "さむくなかった",
        "寒くなかった",
        "さむくなかったです",
        "寒くなかったです",
      ],
      answer: "さむくなかった",
      explain: "い-adj past negative: くない → くなかった.",
    },
    {
      type: "mcq",
      topic: "い-adj + noun",
      prompt: "“a new car” =",
      sub: "",
      options: [
        "あたらしい くるま",
        "あたらしいな くるま",
        "あたらしの くるま",
        "あたらしく くるま",
      ],
      answer: "あたらしい くるま",
      explain: "い-adjectives attach directly to the noun — no な, no の.",
    },
    {
      type: "short",
      topic: "いい (irregular)",
      prompt: "Negative of 「いい」 (good) = “not good”.",
      sub: "",
      accept: ["よくない", "よくないです"],
      answer: "よくない",
      explain: "いい conjugates from よい: よくない (NOT いくない).",
    },
    {
      type: "short",
      topic: "いい (irregular)",
      prompt: "Past of 「いい」 (good) = “was good”.",
      sub: "",
      accept: ["よかった", "よかったです"],
      answer: "よかった",
      explain: "いい → past よかった (from よい).",
    },
    {
      type: "mcq",
      topic: "〜はどうですか",
      prompt: "「コーヒーは どうですか」 means…",
      sub: "",
      options: [
        "How about coffee? / How is the coffee?",
        "Where is the coffee?",
        "Do you have coffee?",
        "Is this coffee?",
      ],
      answer: "How about coffee? / How is the coffee?",
      explain: "〜は どうですか asks for an opinion or makes a suggestion.",
    },
    {
      type: "mcq",
      topic: "が (but)",
      prompt: "「この へやは たかいですが、ひろいです。」 — が here means…",
      sub: "",
      options: ["but", "and so", "because", "or"],
      answer: "but",
      explain: "Clause + が, clause = “…, but …” (contrast).",
    },
    {
      type: "short",
      topic: "い-adj negative",
      prompt: "Negative of 「おもしろい」 = “not interesting”.",
      sub: "",
      accept: [
        "おもしろくない",
        "面白くない",
        "おもしろくないです",
        "面白くないです",
      ],
      answer: "おもしろくない",
      explain: "おもしろい → おもしろくない.",
    },
  ],
};

// Expose for the quiz engine (loaded via <script> before app.js).
window.REVIEW = REVIEW;
